steps:
  - label: "Generate result.txt"
    plugins:
      docker#v5.5.0:
        image: "python:3.13"
    command:
      - echo "--- Current directory:"
      - pwd
      - echo "--- Python version:"
      - python3 --version
      - echo "--- Installing loremipsum package:"
      - pip install loremipsum
      - echo "--- Installed packages:"
      - pip list
      - echo "--- Generating result.txt:"
      - python3 -c "import loremipsum; open('result.txt', 'w').write(loremipsum.sentence(max_char=20))"
      - echo "--- Files after execution:"
      - ls -la
      - echo "--- Result contents:"
      - cat result.txt
      - echo "--- Annotating result:"
      - buildkite-agent annotate --style "info" "$(cat result.txt)"
    artifact_paths:
      - "result.txt"
    agents:
      queue: "default"

  - label: "Generate paragraph.txt"
    plugins:
      docker#v5.5.0:
        image: "python:3.13"
    command:
      - echo "--- Installing loremipsum package:"
      - pip install loremipsum
      - echo "--- Generating paragraph.txt:"
      - python3 -c "import loremipsum; open('paragraph.txt', 'w').write(loremipsum.paragraph(max_char=100))"
      - echo "--- Files after execution:"
      - ls -la
      - echo "--- Paragraph contents:"
      - cat paragraph.txt
      - echo "--- Annotating paragraph:"
      - buildkite-agent annotate --style "info" "$(cat paragraph.txt)"
    artifact_paths:
      - "paragraph.txt"
    agents:
      queue: "default"
    depends_on:
      - "Generate result.txt"
